Repository nutriverse/mwana, pull requests merged in 2024-11, with the labels that each got.

#78 update workflows
  .github/workflows/R-CMD-check.yaml
Labels: ci/cd

#79 uptick version to non-dev
  DESCRIPTION
Labels: ci/cd

#80 update NEWS.md
  NEWS.md
Labels: documentation

#81 uptick version to dev 0.1.0.9000
  DESCRIPTION
Labels: documentation

#84 add high resolution logo; fix #82
  man/figures/logo.png
Labels: documentation, enhancement

#85 Prevalence estimates based on WFHZ
  NAMESPACE
  R/case_definitions.R
  R/mwana-package.R
  R/plausibility_check_mfaz.R
  R/plausibility_check_muac.R
  R/prev_define_wasting.R
  R/prev_wasting_combined.R
  R/prev_wasting_mfaz.R
  R/prev_wasting_muac.R
  R/prev_wasting_probit.R
  R/prev_wasting_wfhz.R
  R/prevalence_wfhz.R
  R/utils.R
  README.md
  README.qmd
  inst/CITATION
  man/apply_cdc_age_weighting.Rd
  man/case_definition.Rd
  man/classify_wasting_for_cdc_approach.Rd
  man/combined_prevalence.Rd
  man/compute_muac_prevalence.Rd
  man/compute_weighted_prevalence.Rd
  man/define_wasting.Rd
  man/mw_estimate_prev_wasting_wfhz.Rd
  man/mw_plausibility_check_mfaz.Rd
  man/mw_plausibility_check_muac.Rd
  man/outliers.Rd
  man/prevalence.Rd
  man/probit-method.Rd
  man/recode_muac.Rd
  man/tell_muac_analysis_strategy.Rd
  pkgdown/_pkgdown.yml
  tests/testthat/test-case_definitions.R
  tests/testthat/test-prev_define_wasting.R
  tests/testthat/test-prev_wasting_combined.R
  tests/testthat/test-prev_wasting_mfaz.R
  tests/testthat/test-prev_wasting_muac.R
  tests/testthat/test-prev_wasting_probit.R
  tests/testthat/test-prev_wasting_wfhz.R
  tests/testthat/test-prevalence_wfhz.R
  vignettes/plausibility.qmd
  vignettes/prevalence.qmd
Labels: question, refactor, testing

#91 Prev combined
  NAMESPACE
  R/prev_wasting_combined.R
  R/prev_wasting_mfaz.R
  R/prev_wasting_muac.R
  R/prev_wasting_wfhz.R
  R/utils.R
  man/combined_prevalence.Rd
  man/mw_estimate_prevalence_combined.Rd
  man/outliers.Rd
  man/prev-muac.Rd
  pkgdown/_pkgdown.yml
  tests/testthat/test-prev_wasting_combined.R
  tests/testthat/test-prev_wasting_mfaz.R
  tests/testthat/test-prev_wasting_muac.R
  tests/testthat/test-prev_wasting_wfhz.R
  vignettes/prevalence.qmd
Labels: analysis, documentation, refactor, testing

#93 Prev screening
  DESCRIPTION
  NAMESPACE
  R/prev_wasting_mfaz.R
  R/prev_wasting_muac.R
  R/prev_wasting_screening.R
  R/utils.R
  README.md
  README.qmd
  inst/CITATION
  man/mw_estimate_prevalence_screening.Rd
  man/mwana-package.Rd
  man/prev-muac.Rd
  man/recode_muac.Rd
  pkgdown/_pkgdown.yml
  tests/testthat/test-prev_wasting_muac.R
  tests/testthat/test-prev_wasting_screening.R
  vignettes/prevalence.qmd
Labels: analysis, documentation, enhancement, testing

#96 Tweaks and uptick dev version to 0.2.0.9000
  DESCRIPTION
  NAMESPACE
  R/data.R
  R/ipc_amn_check.R
  R/mwana-package.R
  R/plausibility_check_mfaz.R
  R/plausibility_check_muac.R
  R/plausibility_check_wfhz.R
  R/prev_define_wasting.R
  R/prev_wasting_combined.R
  R/prev_wasting_mfaz.R
  R/prev_wasting_muac.R
  R/prev_wasting_screening.R
  R/prev_wasting_wfhz.R
  R/quality_raters.R
  README.md
  README.qmd
  man/anthro.03.Rd
  man/anthro.04.Rd
  man/define_wasting.Rd
  man/mw_check_ipcamn_ssreq.Rd
  man/mw_estimate_prevalence_combined.Rd
  man/mw_estimate_prevalence_mfaz.Rd
  man/mw_estimate_prevalence_screening.Rd
  man/mw_estimate_prevalence_wfhz.Rd
  man/mw_neat_output_mfaz.Rd
  man/mw_neat_output_muac.Rd
  man/mw_neat_output_wfhz.Rd
  man/mw_plausibility_check_mfaz.Rd
  man/mw_plausibility_check_muac.Rd
  man/mw_plausibility_check_wfhz.Rd
  man/prev-muac.Rd
  man/rate_propof_flagged.Rd
  man/rate_std.Rd
  tests/testthat/test-plausibility_check_mfaz.R
  tests/testthat/test-plausibility_check_muac.R
  tests/testthat/test-plausibility_check_wfhz.R
  tests/testthat/test-prev_wasting_probit.R
  vignettes/harvard-cite-them-right-11th-edition.csl
  vignettes/ipc_amn_check.qmd
  vignettes/plausibility.qmd
  vignettes/prevalence.qmd
  vignettes/references.bib
Labels: documentation, enhancement, testing
