Repository nutriverse/mwana, pull requests merged in 2024-10, with the labels that each got.

#29 Readme
  .github/CONTRIBUTING.md
  DESCRIPTION
  README.Rmd
  README.md
  README.qmd
  README_files/libs/DiagrammeR-styles-0.2/styles.css
  README_files/libs/bootstrap/bootstrap-icons.css
  README_files/libs/bootstrap/bootstrap-icons.woff
  README_files/libs/bootstrap/bootstrap.min.css
  README_files/libs/bootstrap/bootstrap.min.js
  README_files/libs/clipboard/clipboard.min.js
  README_files/libs/grViz-binding-1.0.11/grViz.js
  README_files/libs/htmlwidgets-1.6.4/htmlwidgets.js
  README_files/libs/quarto-html/anchor.min.js
  README_files/libs/quarto-html/popper.min.js
  README_files/libs/quarto-html/quarto-syntax-highlighting.css
  README_files/libs/quarto-html/quarto.js
  README_files/libs/quarto-html/tippy.css
  README_files/libs/quarto-html/tippy.umd.min.js
  README_files/libs/viz-1.8.2/viz.js
  inst/WORDLIST
  man/figures/README-ipccheckr_workflow-1.png
  man/figures/README-worflow-1.png
  man/ipccheckr-package.Rd
  mwana.Rproj
Labels: documentation

#43 Vignettes
  .Rbuildignore
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/pr-commands.yaml
  .github/workflows/test-coverage.yaml
  .gitignore
  DESCRIPTION
  R/age.R
  README.Rmd
  README.md
  README.qmd
  README_files/libs/DiagrammeR-styles-0.2/styles.css
  README_files/libs/bootstrap/bootstrap-icons.css
  README_files/libs/bootstrap/bootstrap-icons.woff
  README_files/libs/bootstrap/bootstrap.min.css
  README_files/libs/bootstrap/bootstrap.min.js
  README_files/libs/clipboard/clipboard.min.js
  README_files/libs/grViz-binding-1.0.11/grViz.js
  README_files/libs/htmlwidgets-1.6.4/htmlwidgets.js
  README_files/libs/quarto-html/anchor.min.js
  README_files/libs/quarto-html/popper.min.js
  README_files/libs/quarto-html/quarto-syntax-highlighting.css
  README_files/libs/quarto-html/quarto.js
  README_files/libs/quarto-html/tippy.css
  README_files/libs/quarto-html/tippy.umd.min.js
  README_files/libs/viz-1.8.2/viz.js
  _pkgdown.yml
  inst/WORDLIST
  man/figures/README-worflow-1.png
  man/ipccheckr-package.Rd
  man/process_age.Rd
  pkgdown/_pkgdown.yml
  vignettes/.gitignore
  vignettes/plausiblity.Rmd
  vignettes/plausiblity.qmd
  vignettes/prevalence.Rmd
  vignettes/prevalence.qmd
  vignettes/sample_size.Rmd
  vignettes/sample_size.qmd
Labels: documentation

#50 create dev branch; fix #42; fix #47; fix #49
  .gitignore
  NEWS.md
  README_files/figure-commonmark/workflow-1.png
Labels: documentation, infrastructure

#53 add code of conduct; fix #48; fix #52
  .Rbuildignore
  .github/CODE_OF_CONDUCT.md
  .github/workflows/test-coverage.yaml
Labels: ci/cd, documentation

#55 correct spelling of plausibility.qmd; fix #54
  .gitignore
  vignettes/plausibility.qmd
Labels: bug, documentation

#56 Re-factor of function to wrangle age
  .Rbuildignore
  DESCRIPTION
  NAMESPACE
  R/age.R
  R/ipccheckr-package.R
  R/pretty_tables.R
  R/prevalence_combined.R
  R/prevalence_muac.R
  R/quality_auditors.R
  R/stattests.R
  R/utils.R
  R/wrangle_age.R
  R/wranglers.R
  README.md
  README.qmd
  README_files/figure-commonmark/workflow-1.png
  inst/WORDLIST
  man/apply_cdc_age_weighting.Rd
  man/combined_prevalence.Rd
  man/compute_age_in_months.Rd
  man/compute_month_to_days.Rd
  man/get_age_months.Rd
  man/mw_stattest_ageratio.Rd
  man/mw_wrangle_age.Rd
  man/plausibility-check.Rd
  man/pretty_table.Rd
  man/process_age.Rd
  man/wrangler.Rd
  pkgdown/_pkgdown.yml
  tests/testthat/test-age.R
  tests/testthat/test-pretty_tables.R
  tests/testthat/test-prevalence_combined.R
  tests/testthat/test-prevalence_muac.R
  tests/testthat/test-quality_auditors.R
  tests/testthat/test-stattests.R
  tests/testthat/test-utils.R
  tests/testthat/test-wrangle_age.R
  tests/testthat/test-wranglers.R
  vignettes/plausibility.qmd
  vignettes/prevalence.qmd
Labels: data cleaning, refactor

#57 Re-factor functions to wrangle wfhz and muac data
  NAMESPACE
  R/ipccheckr-package.R
  R/pretty_tables.R
  R/prevalence_combined.R
  R/prevalence_mfaz.R
  R/prevalence_muac.R
  R/prevalence_wfhz.R
  R/quality_auditors.R
  R/stattests.R
  R/utils.R
  R/wrangle_age.R
  R/wrangle_muac.R
  R/wrangle_wfhz.R
  R/wranglers.R
  README.md
  README.qmd
  README_files/figure-commonmark/workflow-1.png
  inst/WORDLIST
  man/combined_prevalence.Rd
  man/get_age_months.Rd
  man/mw_stattest_ageratio.Rd
  man/mw_wrangle_age.Rd
  man/mw_wrangle_muac.Rd
  man/mw_wrangle_wfhz.Rd
  man/outliers.Rd
  man/plausibility-check.Rd
  man/pretty_table.Rd
  man/prevalence.Rd
  man/recode_muac.Rd
  man/wrangler.Rd
  pkgdown/_pkgdown.yml
  tests/testthat/test-pretty_tables.R
  tests/testthat/test-prevalence_combined.R
  tests/testthat/test-prevalence_muac.R
  tests/testthat/test-prevalence_wfhz.R
  tests/testthat/test-quality_auditors.R
  tests/testthat/test-stattests.R
  tests/testthat/test-utils.R
  tests/testthat/test-wrangle_age.R
  tests/testthat/test-wrangle_muac.R
  tests/testthat/test-wrangle_wfhz.R
  tests/testthat/test-wranglers.R
  vignettes/plausibility.qmd
  vignettes/prevalence.qmd
  vignettes/sample_size.qmd
Labels: documentation, refactor, testing
