Repository nutriverse/mwana, pull requests merged in 2024-12, with the labels that each got.

#132 edit fix to vignette code annotation issue
  DESCRIPTION
  NEWS.md
  vignettes/ipc_amn_check.Rmd
Labels: documentation

#133 pre-render plausibility vignette
  pkgdown/_pkgdown.yml
  vignettes/plausibility.Rmd
  vignettes/plausibility.qmd.orig
Labels: documentation

#135 Fix count prev
  .gitignore
  R/prev_wasting_combined.R
  R/prev_wasting_mfaz.R
  R/prev_wasting_muac.R
  R/prev_wasting_screening.R
  R/prev_wasting_wfhz.R
  R/wrangle_wfhz.R
  tests/testthat/test-prev_wasting_combined.R
  tests/testthat/test-prev_wasting_mfaz.R
  tests/testthat/test-prev_wasting_muac.R
  tests/testthat/test-prev_wasting_wfhz.R
Labels: bug, refactor

#143 general website updates; fix #136; fix #141; fix #139; fix #142
  .Rbuildignore
  .github/workflows/netlify.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  pkgdown/_pkgdown.yml
Labels: ci/cd, documentation, testing
